Issue 195/one task
enonic/enonic-react4xp pull request #205
Opened 2023-03-31 09:41 UTC by ComLock

2023-03-31 11:44 UTC, rymsha approved these changes

2023-03-31 12:14 UTC, alansemenov approved these changes

2023-03-31 20:41 UTC, rymsha requested changes
tsup.config.client.ts
tsup.config.executor.ts
need env fixes, too
```
const DIR_PATH_ABSOLUTE_PROJECT = process.env.DIR_PATH_ABSOLUTE_PROJECT
```

2023-04-03 13:14 UTC, rymsha approved these changes

2023-04-03 13:58 UTC, merged